language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- npm install -g istanbul
after_install:
- npm install -g karma-cli
script:
- istanbul cover specifications/test && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
env:
  global:
  - secure: AUb3B1lZpdVWa4O2uRbbSnWud9sMgoMlcKgS5Mktbkp4Xoi90b8H/xi6NDUaCtzm6Zcw5lIN/X//LjmvjRG+BJri4wmzhAq8QxoV6ZDn5/C9KGx542TyCqp5oXO8+e4FWbpIr/Wsl9bl62Xyu+URDAd0pIQjEJgCP1lADcEqnthHgla6QxK8JD9zAVnWsyMg/9EmUwVPyuj5svOaoMsxFNstRphbSeUfgGQtEgilUCQTiZv22TE6BSZgkbJJuFyEdpcThwSG0HOFGZIb3HRC81A+D/3bmDevI5rCdDjP5BCJde7ffij7VqQSZc6C9wgYYRixjhKeDT+OtTIzLbpgXbshYPn2J7wMXZDQIltO96hmmlEWuFcRPHObDGnz1/ym0MzDNdsv7CD7ZMLSmDlYYzZ8AioGBvZ6QfTTbb/VGogDuJGKpMEJhCqrUb/9T1+6MH+VlNjlOGBhOCV+IvXzDX1bb2nCqGKLoa5AfRf9/8p+D/0H5ItNEeQVTOaGx4fmfW1RtJzhFdWu0RhOrGGIdCNKdHaBzho2m0NLapSmJ9dkPF+n9MbJso7HAINZ4l1M6r0v4cmoWFrI9zIvm+waCILLyJtDLiZIHNXbvVoIHhilW80uY7AQzxhv9UPUY7yR4mn2Koye6ET3DVrFAs6nSyO4IEBseTLn4CY6Av/eZyI=
  - secure: o/woTXdr+cAnQZxM4tySu6k0O0O/AYrvMuR6tFH/GIFE0Xqv6ogJ3VDVHlh2FvpQEahQ5BVmlBnJHhjJXrCVveqsTFDylo5nJe9wuUW51KOOUy07cE9Fyn9ki/EEWixKMe5cINzieCFgESUK2Frtk8e0NfYhGvfMqnvGda1tmdfwWQ7sTqfAXXUswjndbchGzxsGlpn/uMmiCXuB+6EqAqUmV3BwyiSGGgH6U7hPgY4RQy9KIJpX4EYwMhLfvHMiGPk3i9SjQvWmo02PLaE2tPHSSOjlrMQ5UDE3aqEVtw9PLlXjGrmWhnJNTOKr99erCrOIWrtyo5/CA9EtlNbyKxsPl2yUs7RR/IzKH1TF46aIM0mpUHqJ5sXSiDzYwhvKG/5Uj27yOgEaeRP6ljfjGoUTIa4RQYY4aMIpyYwyDgMU5grgr565tZ/hvCXDOZdJn87eZX9yO5GMUKceHeWWjtu1keob8TlxfUX3ztI54SXjRx6JWqqHYLNomh6q3nRxedsjEZFT+575qmmTvPWr3h8Xa8Ot35mgGf5imzp5Rviszjcaji1hTyMeo1IaLiChWDz388Gkyjl5FRMwBVywNjArz+1laHugIpV8cDhlCc0F8guYgKMWHnvprUq5CPpged9x/PxMxDVIw/tvqSaaTFrsy4tgB/RfKBGbJwRXcA8=